### ISSUE TITLE
Default for metadata

### ISSUE THREAD

**Issue by michaelwitting** [michaelwitting/MsBackendMassbank#7]
Shall the metadata be read by default or not?
Ideas @jorainer, @sneumann, @schymane?

**Comment by schymane** [comment]
I implemented a function in ReSOLUTION that by default took a select (relatively common) set of metadata, and left users the option to define other fields if desired ... that may be the way around this ... 

https://github.com/schymane/ReSOLUTION/blob/master/R/MassBankRecordeR.R

https://github.com/schymane/ReSOLUTION/blob/master/R/MassBankRecordeR.R#L66

**Comment by michaelwitting** [comment]
@schymane I like this idea. Currently, there is the option to define, which metadata blocks shall be read, e.g. all the analytical chemistry. In future by default all the entries you mentioned can be read and then the user can define which additional blocks he wants. I don't want to get the user to define it down to single entries, but I think blocks is okay.

**Comment by michaelwitting** [comment]
I updated everything that the same fields as mentioned by @schymane are read as default. Other metadata blocks can be added on demand.
