### ISSUE TITLE
Fix when missing rtime

### ISSUE THREAD

**Issue by michaelwitting** [michaelwitting/MsBackendMassbank#8]
Some records don't have `rtime`. Add 0 as default value when `rtime` is missing

**Comment by jorainer** [comment]
To be consistent with `R` in general I would use `NA_real_` instead of `0` for *missing*.

**Comment by michaelwitting** [comment]
But is `Spectra` accepting that?

**Comment by michaelwitting** [comment]
Okay... sorted it out. Now with `NA_real_`
